"""moment unique key includes model

Revision ID: 235df0a0d561
Revises: 9d9b77abf037
Create Date: 2026-08-11 10:39:01.935771

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '235df0a0d561'
down_revision: str | None = '9d9b77abf037'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_moment_video_version_start'), 'moment', type_='unique')
    op.create_unique_constraint('uq_moment_video_version_model_start', 'moment', ['video_id', 'schema_version', 'model', 'start_sec'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_moment_video_version_model_start', 'moment', type_='unique')
    op.create_unique_constraint(op.f('uq_moment_video_version_start'), 'moment', ['video_id', 'schema_version', 'start_sec'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
