"""moment

Revision ID: 9d9b77abf037
Revises: f49cceae8e42
Create Date: 2026-08-11 01:45:17.975985

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9d9b77abf037'
down_revision: str | None = 'f49cceae8e42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('start_sec', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('end_sec', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_strength', sa.String(length=16), nullable=True),
    sa.Column('relevance', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'schema_version', 'start_sec', name='uq_moment_video_version_start')
    )
    op.create_index(op.f('ix_moment_schema_version'), 'moment', ['schema_version'], unique=False)
    op.create_index(op.f('ix_moment_video_id'), 'moment', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moment_video_id'), table_name='moment')
    op.drop_index(op.f('ix_moment_schema_version'), table_name='moment')
    op.drop_table('moment')
    # ### end Alembic commands ###
