"""video, ingest_job, llm_call

Revision ID: af9ceaab2fcd
Revises: 0001
Create Date: 2026-08-10 21:06:15.427783

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af9ceaab2fcd'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=16), server_default=sa.text("'douyin'"), nullable=False),
    sa.Column('aweme_id', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'aweme_id', name='uq_video_platform_aweme')
    )
    op.create_index(op.f('ix_video_created_at'), 'video', ['created_at'], unique=False)
    op.create_table('ingest_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('short_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('failure_kind', sa.String(length=16), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_job_created_at'), 'ingest_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_ingest_job_status'), 'ingest_job', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_job_video_id'), 'ingest_job', ['video_id'], unique=False)
    op.create_table('llm_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('task', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_task'), 'llm_call', ['task'], unique=False)
    op.create_index(op.f('ix_llm_call_video_id'), 'llm_call', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_video_id'), table_name='llm_call')
    op.drop_index(op.f('ix_llm_call_task'), table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_index(op.f('ix_ingest_job_video_id'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_status'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_created_at'), table_name='ingest_job')
    op.drop_table('ingest_job')
    op.drop_index(op.f('ix_video_created_at'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
